export const ROUTE_PATHS = {
  main: '/',
  login: '/login',
  registration: '/registration',
  profile: '/profile',
  profileEdit: '/profile/edit',
  orderHistory: '/order-history',
  cart: '/cart',
  product: '/product',
  catalog: '/catalog',
  catalogCategories: '/catalog/categories',
  catalogFilters: '/catalog/filters',
  order: '/order',
  orderConfirm: '/order-confirm',
} as const;
